//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Media.Query;

namespace MIT.ECSR.Core.ProgramItem.Query
{

    public class GetProgramItemByIdRequest : IRequest<ObjectResponse<ProgramItemResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetProgramItemByIdHandler : IRequestHandler<GetProgramItemByIdRequest, ObjectResponse<ProgramItemResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        private readonly IMediator _mediator;
        public GetProgramItemByIdHandler(
            ILogger<GetProgramItemByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context,
            IMediator mediator)
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
            _mediator = mediator;
        }
        public async Task<ObjectResponse<ProgramItemResponse>> Handle(GetProgramItemByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<ProgramItemResponse> result = new ObjectResponse<ProgramItemResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.TrsProgramItem>().Where(d => d.Id == request.Id).Include(d => d.TrsPenawaranItem).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<ProgramItemResponse>(item);
                    var lampiran = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "ITEM_PROGRAM" });
                    if (lampiran.Succeeded)
                        result.Data.Lampiran = lampiran.List;

                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.TrsProgramItem {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail ProgramItem", request.Id);
                result.Error("Failed Get Detail ProgramItem", ex.Message);
            }
            return result;
        }
    }
}

