//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MIT.ECSR.Shared.Attributes;
using System.ComponentModel.DataAnnotations;

namespace MIT.ECSR.Core.Request
{
    public class RegisterRequest : UserRequest
    {
        [Required]
        public string Password { get; set; }
    }
    public partial class UserRequest
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public int IdRole { get; set; }
        [Required]
        public string Fullname{ get; set; }
		[Required]
		public string Mail{ get; set; }
		public string PhoneNumber{ get; set; }
		public string Password { get; set; }
        public FileObject Photo { get; set; }
        public PerusahaanRequest Perusahaan { get; set; }

    }
}

