//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MIT.ECSR.Shared.Attributes;
using System.ComponentModel.DataAnnotations;

namespace MIT.ECSR.Core.Request
{
    public partial class UsulanRequest
    {
        [Required]
        public string Deskripsi { get; set; }
        [Required]
        public string Lokasi { get; set; }
        [Required]
        public int IdJenisProgram { get; set; }
        [Required]
        public string NamaProgram { get; set; }
        [Required]
        public DateTime StartPelaksanaan { get; set; }
        [Required]
        public DateTime EndPelaksanaan { get; set; }
        public FileObject Photo { get; set; }

    }
}

