//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.Opd.Query
{

    public class GetOpdByIdRequest : IRequest<ObjectResponse<OpdResponse>>
    {
        [Required]
        public int Id { get; set; }
    }
    internal class GetOpdByIdHandler : IRequestHandler<GetOpdByIdRequest, ObjectResponse<OpdResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetOpdByIdHandler(
            ILogger<GetOpdByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<OpdResponse>> Handle(GetOpdByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<OpdResponse> result = new ObjectResponse<OpdResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.RefOpd>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<OpdResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.RefOpd {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Opd", request.Id);
                result.Error("Failed Get Detail Opd", ex.Message);
            }
            return result;
        }
    }
}

