//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.Kegiatan.Query
{

    public class GetKegiatanByIdRequest : IRequest<ObjectResponse<KegiatanResponse>>
    {
        [Required]
        public int Id { get; set; }
    }
    internal class GetKegiatanByIdHandler : IRequestHandler<GetKegiatanByIdRequest, ObjectResponse<KegiatanResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetKegiatanByIdHandler(
            ILogger<GetKegiatanByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<KegiatanResponse>> Handle(GetKegiatanByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<KegiatanResponse> result = new ObjectResponse<KegiatanResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.RefKegiatan>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<KegiatanResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.RefKegiatan {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Kegiatan", request.Id);
                result.Error("Failed Get Detail Kegiatan", ex.Message);
            }
            return result;
        }
    }
}

