//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.SubProgram.Query
{

    public class GetSubProgramByIdRequest : IRequest<ObjectResponse<SubProgramResponse>>
    {
        [Required]
        public int Id { get; set; }
    }
    internal class GetSubProgramByIdHandler : IRequestHandler<GetSubProgramByIdRequest, ObjectResponse<SubProgramResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetSubProgramByIdHandler(
            ILogger<GetSubProgramByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<SubProgramResponse>> Handle(GetSubProgramByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<SubProgramResponse> result = new ObjectResponse<SubProgramResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.RefSubProgram>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<SubProgramResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.RefSubProgram {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail SubProgram", request.Id);
                result.Error("Failed Get Detail SubProgram", ex.Message);
            }
            return result;
        }
    }
}

