//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Helper;

namespace MIT.ECSR.Core.Media.Query
{

    public class DownloadMediaRequest : IRequest<ObjectResponse<FileObject>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class DownloadMediaHandler : IRequestHandler<DownloadMediaRequest, ObjectResponse<FileObject>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public DownloadMediaHandler(
            ILogger<DownloadMediaHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<FileObject>> Handle(DownloadMediaRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<FileObject> result = new ObjectResponse<FileObject>();
            try
            {
                var item = await _context.Entity<TrsMedia>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    string path_dokumen = Path.Combine("Media", item.Tipe, item.Id.ToString());

                    if (!File.Exists(path_dokumen))
                    {
                        result.NotFound($"File {path_dokumen} Tidak Ditemukan");
                        return result;
                    }
                    byte[] bytes = File.ReadAllBytes(path_dokumen);

                    result.Data = new FileObject()
                    {
                        Base64 = System.Convert.ToBase64String(bytes),
                        Filename = item.FileName
                    };
                    result.OK();
                }
                else
                    result.NotFound($"Id TrsMedia {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Media", request.Id);
                result.Error("Failed Get Detail Media", ex.Message);
            }
            return result;
        }
    }
}

