//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Media.Query;
using MIT.ECSR.Core.Helper;

namespace MIT.ECSR.Core.Program.Query
{

    public class GetProgramByIdRequest : IRequest<ObjectResponse<ProgramDetailResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetProgramByIdHandler : IRequestHandler<GetProgramByIdRequest, ObjectResponse<ProgramDetailResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetProgramByIdHandler(
            ILogger<GetProgramByIdHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _context = context;
        }
        public async Task<ObjectResponse<ProgramDetailResponse>> Handle(GetProgramByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<ProgramDetailResponse> result = new ObjectResponse<ProgramDetailResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.TrsProgram>().Where(d => d.Id == request.Id).Include(d=>d.IdJenisProgramNavigation).Include(d=>d.LokasiNavigation).Include(d=>d.NamaProgramNavigation).Include(d=>d.TrsProgramItem).ThenInclude(s=>s.TrsProgresProgram).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<ProgramDetailResponse>(item);
                    var photo = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "PHOTO_PROGRAM" });
                    if (photo.Succeeded)
                        result.Data.Photo = photo.List.FirstOrDefault();
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.TrsProgram {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Program", request.Id);
                result.Error("Failed Get Detail Program", ex.Message);
            }
            return result;
        }
    }
}

