//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MIT.ECSR.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using MIT.ECSR.Data.Model;

namespace MIT.ECSR.Core.Response
{
    public partial class DatiResponse: IMapResponse<DatiResponse, MIT.ECSR.Data.Model.RefDati>
    {
		public Guid Id{ get; set; }
		public bool Active{ get; set; }
		public string CreateBy{ get; set; }
		public DateTime CreateDate{ get; set; }
		public string KodeDati1{ get; set; }
		public string KodeDati2{ get; set; }
		public string KodeDati3{ get; set; }
		public string KodeDati4{ get; set; }
		public string NamaDati1{ get; set; }
		public string NamaDati2{ get; set; }
		public string NamaDati3{ get; set; }
		public string NamaDati4{ get; set; }
		public string UpdateBy{ get; set; }
		public DateTime? UpdateDate{ get; set; }


        public void Mapping(IMappingExpression<MIT.ECSR.Data.Model.RefDati, DatiResponse> map)
        {
            //use this for mapping
            //map.ForMember(d => d.object, opt => opt.MapFrom(s => s.EF_COLUMN));

        }
    }
}

