//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MIT.ECSR.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;

namespace MIT.ECSR.Core.Response
{
    public partial class ProgresProgramResponse : IMapResponse<ProgresProgramResponse, MIT.ECSR.Data.Model.TrsProgresProgram>
    {
        public Guid Id { get; set; }
        public DateTime TglProgress { get; set; }
        public DateTime? ApprovedAt { get; set; }
        public string ApprovedBy { get; set; }
        public string CreateBy { get; set; }
        public DateTime CreateDate { get; set; }
        public string Deskripsi { get; set; }
        public Guid IdProgramItem { get; set; }
        public string ItemName { get; set; }
        public double Item { get; set; }
        public string SatuanUnit { get; set; }
        public string JenisProgram { get; set; }
        public string NamaProgram { get; set; }
        public string CompanyName { get; set; }
        public string Notes { get; set; }
        public Guid IdProgram { get; set; }
        public int Progress { get; set; }
        public int Status { get; set; }
        public List<MediaUrl> Lampiran { get; set; }
        public void Mapping(IMappingExpression<MIT.ECSR.Data.Model.TrsProgresProgram, ProgresProgramResponse> map)
        {
            //use this for mapping
            map.ForMember(d => d.IdProgram, opt => opt.MapFrom(s => s.IdProgramItemNavigation.IdProgram))
            .ForMember(d => d.ItemName, opt => opt.MapFrom(s => s.IdProgramItemNavigation.Nama))
            .ForMember(d => d.SatuanUnit, opt => opt.MapFrom(s => s.IdProgramItemNavigation.SatuanUnit))
            .ForMember(d => d.JenisProgram, opt => opt.MapFrom(s => s.IdProgramItemNavigation.IdProgramNavigation.IdJenisProgramNavigation.Name))
            .ForMember(d => d.NamaProgram, opt => opt.MapFrom(s => s.IdProgramItemNavigation.IdProgramNavigation.NamaProgramNavigation.Name))
            .ForMember(d => d.Notes, opt => opt.MapFrom(s => s.Notes))
            .ForMember(d => d.Item, opt => opt.MapFrom(s => s.IdProgramItemNavigation.Jumlah))
            .ForMember(d => d.CompanyName, opt => opt.MapFrom(s => s.IdPerusahaanNavigation.NamaPerusahaan));
        }
    }
}

