//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.UsulanItem.Query
{

    public class GetUsulanItemByIdRequest : IRequest<ObjectResponse<UsulanItemResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetUsulanItemByIdHandler : IRequestHandler<GetUsulanItemByIdRequest, ObjectResponse<UsulanItemResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetUsulanItemByIdHandler(
            ILogger<GetUsulanItemByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<UsulanItemResponse>> Handle(GetUsulanItemByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<UsulanItemResponse> result = new ObjectResponse<UsulanItemResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.TrsUsulanItem>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<UsulanItemResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.TrsUsulanItem {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail UsulanItem", request.Id);
                result.Error("Failed Get Detail UsulanItem", ex.Message);
            }
            return result;
        }
    }
}

