//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Helper;

namespace MIT.ECSR.Core.UsulanItem.Query
{
    public class GetUsulanItemListRequest : ListRequest,IListRequest<GetUsulanItemListRequest>,IRequest<ListResponse<UsulanItemResponse>>
    {
    }
    internal class GetUsulanItemListHandler : IRequestHandler<GetUsulanItemListRequest, ListResponse<UsulanItemResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetUsulanItemListHandler(
            ILogger<GetUsulanItemListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<UsulanItemResponse>> Handle(GetUsulanItemListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<UsulanItemResponse> result = new ListResponse<UsulanItemResponse>();
            try
            {
				var query = _context.Entity<MIT.ECSR.Data.Model.TrsUsulanItem>().AsQueryable();

				#region Filter
				Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, object>> column_sort = null;
				List<Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, bool>>> where = new List<Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				result.List = _mapper.Map<List<UsulanItemResponse>>(data_list);
				result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List UsulanItem", request);
                result.Error("Failed Get List UsulanItem", ex.Message);
            }
            return result;
        }

        #region List Utility
		private (Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, bool>> where, Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, object>> result_order = null;
			Expression<Func<MIT.ECSR.Data.Model.TrsUsulanItem, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
						}
						else
							result_order = (d => d.Id);
					break;
					case "createby" : 
						if(is_where){
							result_where = (d=>d.CreateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CreateBy);
					break;
					case "createdate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CreateDate))
								result_where = (d=>d.CreateDate == _CreateDate);
						}
						else
							result_order = (d => d.CreateDate);
					break;
					case "idusulan" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdUsulan))
								result_where = (d=>d.IdUsulan == _IdUsulan);
						}
						else
							result_order = (d => d.IdUsulan);
					break;
					case "jumlah" : 
						if(is_where){
							if (double.TryParse(search, out var _Jumlah))
								result_where = (d=>d.Jumlah == _Jumlah);
						}
						else
							result_order = (d => d.Jumlah);
					break;
					case "nama" : 
						if(is_where){
							result_where = (d=>d.Nama.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.Nama);
					break;
					case "rupiah" : 
						if(is_where){
							if (double.TryParse(search, out var _Rupiah))
								result_where = (d=>d.Rupiah == _Rupiah);
						}
						else
							result_order = (d => d.Rupiah);
					break;
					case "satuanunit" : 
						if(is_where){
							result_where = (d=>d.SatuanUnit.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.SatuanUnit);
					break;
					case "updateby" : 
						if(is_where){
							result_where = (d=>d.UpdateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.UpdateBy);
					break;
					case "updatedate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _UpdateDate))
								result_where = (d=>d.UpdateDate == _UpdateDate);
						}
						else
							result_order = (d => d.UpdateDate);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

