//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using DocumentFormat.OpenXml.Spreadsheet;
using MIT.ECSR.Core.Media.Query;

namespace MIT.ECSR.Core.User.Query
{

    public class GetUserByIdRequest : IRequest<ObjectResponse<UserDetailResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetUserByIdHandler : IRequestHandler<GetUserByIdRequest, ObjectResponse<UserDetailResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetUserByIdHandler(
            ILogger<GetUserByIdHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _context = context;
        }
        public async Task<ObjectResponse<UserDetailResponse>> Handle(GetUserByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<UserDetailResponse> result = new ObjectResponse<UserDetailResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.SetUser>().Where(d => d.Id == request.Id)
                    .Include(d=>d.IdRoleNavigation).Include(d=>d.MstPerusahaan).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<UserDetailResponse>(item);
                    if (item.MstPerusahaan != null && item.MstPerusahaan.Count > 0)
                    {
                        result.Data.Perusahaan = new PerusahaanResponse();
                        var perusahaan = item.MstPerusahaan.FirstOrDefault();
                        result.Data.Perusahaan.Id = perusahaan.Id;
                        result.Data.Perusahaan.Alamat = perusahaan.Alamat;
                        result.Data.Perusahaan.BidangUsaha = perusahaan.BidangUsaha;
                        result.Data.Perusahaan.NamaPerusahaan = perusahaan.NamaPerusahaan;
                        result.Data.Perusahaan.JenisPerseroan = perusahaan.JenisPerseroan;
                        result.Data.Perusahaan.Nib = perusahaan.Nib;
                        result.Data.Perusahaan.Npwp = perusahaan.Npwp;
                        result.Data.Perusahaan.UpdateBy = perusahaan.UpdateBy;
                        result.Data.Perusahaan.UpdateDate = perusahaan.UpdateDate;
                        result.Data.Perusahaan.CreateDate = perusahaan.CreateDate;
                        result.Data.Perusahaan.CreateBy = perusahaan.CreateBy;
                    }
                    var photo = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "PHOTO_USER" });
                    if (photo.Succeeded)
                        result.Data.Photo = photo.List.FirstOrDefault();
                    result.OK();
                }
                else
                    result.NotFound($"Id User {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail User", request.Id);
                result.Error("Failed Get Detail User", ex.Message);
            }
            return result;
        }
    }
}

