//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.Perusahaan.Query
{

    public class GetPerusahaanByIdRequest : IRequest<ObjectResponse<PerusahaanResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetPerusahaanByIdHandler : IRequestHandler<GetPerusahaanByIdRequest, ObjectResponse<PerusahaanResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetPerusahaanByIdHandler(
            ILogger<GetPerusahaanByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<PerusahaanResponse>> Handle(GetPerusahaanByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<PerusahaanResponse> result = new ObjectResponse<PerusahaanResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.MstPerusahaan>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<PerusahaanResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.SetPerusahaan {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Perusahaan", request.Id);
                result.Error("Failed Get Detail Perusahaan", ex.Message);
            }
            return result;
        }
    }
}

