//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;

namespace MIT.ECSR.Core.Dati.Query
{

    public class GetDatiByIdRequest : IRequest<ObjectResponse<DatiResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetDatiByIdHandler : IRequestHandler<GetDatiByIdRequest, ObjectResponse<DatiResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetDatiByIdHandler(
            ILogger<GetDatiByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<DatiResponse>> Handle(GetDatiByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<DatiResponse> result = new ObjectResponse<DatiResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.RefDati>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<DatiResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.RefDati {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Dati", request.Id);
                result.Error("Failed Get Detail Dati", ex.Message);
            }
            return result;
        }
    }
}

