//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Media.Query;
using DocumentFormat.OpenXml.Spreadsheet;

namespace MIT.ECSR.Core.ProgresProgram.Query
{

    public class GetProgresProgramByIdRequest : IRequest<ObjectResponse<ProgresProgramResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetProgresProgramByIdHandler : IRequestHandler<GetProgresProgramByIdRequest, ObjectResponse<ProgresProgramResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetProgresProgramByIdHandler(
            ILogger<GetProgresProgramByIdHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _context = context;
        }
        public async Task<ObjectResponse<ProgresProgramResponse>> Handle(GetProgresProgramByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<ProgresProgramResponse> result = new ObjectResponse<ProgresProgramResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.TrsProgresProgram>().Where(d => d.Id == request.Id)
                    .Include(d=>d.IdProgramItemNavigation)
                    .ThenInclude(d => d.IdProgramNavigation)
                    .ThenInclude(d => d.IdJenisProgramNavigation)
                    .Include(d => d.IdPerusahaanNavigation)
                    .Include(d => d.IdProgramItemNavigation)
                    .ThenInclude(d => d.IdProgramNavigation)
                    .ThenInclude(d => d.NamaProgramNavigation)
                .FirstOrDefaultAsync();

                if (item != null)
                {
                    result.Data = _mapper.Map<ProgresProgramResponse>(item);
                    var lampiran = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "PROGRESS" });
                    if (lampiran.Succeeded)
                        result.Data.Lampiran = lampiran.List;
                    result.OK();

                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.TrsProgresProgram {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail ProgresProgram", request.Id);
                result.Error("Failed Get Detail ProgresProgram", ex.Message);
            }
            return result;
        }
    }
}

