//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Dati.Query;
using Microsoft.AspNetCore.Authorization;

namespace MIT.ECSR.API.Controllers
{
    public partial class DatiController : BaseController<DatiController>
    {
        [AllowAnonymous]
        [HttpGet(template: "get/{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            return Wrapper(await _mediator.Send(new GetDatiByIdRequest() { Id = id }));
        }

        [AllowAnonymous]
        [HttpPost(template: "list")]
        public async Task<IActionResult> List([FromBody] ListRequest request)
        {
            var list_request = _mapper.Map<GetDatiListRequest>(request);
            return Wrapper(await _mediator.Send(list_request));
        }
        
    }
}

