//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Kegiatan.Query;
using MIT.ECSR.Core.Request;
using MIT.ECSR.Core.Kegiatan.Command;
using Microsoft.AspNetCore.Authorization;

namespace MIT.ECSR.API.Controllers
{
    public partial class KegiatanController : BaseController<KegiatanController>
    {
        [AllowAnonymous]
        [HttpGet(template: "get/{id}")]
        public async Task<IActionResult> GetById(int id)
        {
            return Wrapper(await _mediator.Send(new GetKegiatanByIdRequest() { Id = id }));
        }

        [AllowAnonymous]
        [HttpPost(template: "list")]
        public async Task<IActionResult> List([FromBody] ListRequest request)
        {
            var list_request = _mapper.Map<GetKegiatanListRequest>(request);
            return Wrapper(await _mediator.Send(list_request));
        }

        [HttpPost(template: "add")]
        public async Task<IActionResult> Add([FromBody] KegiatanRequest request)
        {
            var add_request = _mapper.Map<AddKegiatanRequest>(request);
            add_request.Inputer = Token.User.Username;
            return Wrapper(await _mediator.Send(add_request));
        }

        [HttpPut(template: "edit/{id}")]
        public async Task<IActionResult> Edit(int id, [FromBody] KegiatanRequest request)
        {
            var edit_request = _mapper.Map<EditKegiatanRequest>(request);
            edit_request.Id = id;
            edit_request.Inputer = Token.User.Username;
            return Wrapper(await _mediator.Send(edit_request));
        }

        [HttpDelete(template: "delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            return Wrapper(await _mediator.Send(new DeleteKegiatanRequest() { Id = id, Inputer = Token.User.Username }));
        }

        
        [HttpPut(template: "active/{id}/{value}")]
        public async Task<IActionResult> Active(int id, bool value)
        {
            return Wrapper(await _mediator.Send(new ActiveKegiatanRequest() { Id = id, Active = value, Inputer = Token.User.Username }));
        }
        
    }
}

