//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Helper;
using MIT.ECSR.Core.Request;
using MIT.ECSR.Core.Media.Command;
using MIT.ECSR.Data.Model;

namespace MIT.ECSR.Core.ProgramItem.Command
{

    #region Request
    public class AddProgramItemMapping: Profile
    {
        public AddProgramItemMapping()
        {
            CreateMap<AddProgramItemRequest, ProgramItemRequest>().ReverseMap();
        }
    }
    public class AddProgramItemRequest :ProgramItemRequest, IMapRequest<MIT.ECSR.Data.Model.TrsProgramItem, AddProgramItemRequest>,IRequest<StatusResponse>
    {
        [Required]
        public string Inputer { get; set; }
        public void Mapping(IMappingExpression<AddProgramItemRequest, MIT.ECSR.Data.Model.TrsProgramItem> map)
        {
            //use this for mapping
            //map.ForMember(d => d.EF_COLUMN, opt => opt.MapFrom(s => s.Object));
        }
    }
    #endregion

    internal class AddProgramItemHandler : IRequestHandler<AddProgramItemRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        private readonly IMediator _mediator;

        public AddProgramItemHandler(
            ILogger<AddProgramItemHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context,
            IMediator mediator)
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
            _mediator = mediator;
        }
        public async Task<StatusResponse> Handle(AddProgramItemRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var program = _context.Entity<TrsProgram>().FirstOrDefault(x => x.Id == request.IdProgram);
                if (program == null)
                {
                    result.BadRequest($"Program tidak ditemukan");
                    return result;
                }

                if (program.StartTglPelaksanaan > request.StartTglPelaksanaan || program.EndTglPelaksanaan < request.EndTglPelaksanaan)
                {
                    var startDate = program.StartTglPelaksanaan.ToString("dd MMMM yyyy", new System.Globalization.CultureInfo("id-ID"));
                    var endDate = program.EndTglPelaksanaan.ToString("dd MMMM yyyy", new System.Globalization.CultureInfo("id-ID"));
                    result.BadRequest($"Tanggal Start Pelaksanaan  tidak boleh kurang dari {startDate} dan Tanggal End Pelaksanaan tidak boleh lebih dari {endDate}");
                    return result;
                }

                var data = _mapper.Map<MIT.ECSR.Data.Model.TrsProgramItem>(request);
                data.CreateBy = request.Inputer;
                data.CreateDate = DateTime.Now;
                data.UpdateBy = request.Inputer;
                data.UpdateDate = DateTime.Now;
                var add = await _context.AddSave(data);
                if (add.Success)
                {
                    result.OK();
                    if (request.Lampiran != null)
                    {
                        foreach (var d in request.Lampiran)
                        {
                            result = await _mediator.Send(new UploadMediaRequest()
                            {
                                File = d,
                                Inputer = request.Inputer,
                                Modul = data.Id.ToString(),
                                Tipe = "ITEM_PROGRAM"
                            });
                        }
                    }
                }
                else
                    result.BadRequest(add.Message);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Add ProgramItem", request);
                result.Error("Failed Add ProgramItem", ex.Message);
            }
            return result;
        }
    }
}

