//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Response;
using MIT.ECSR.Core.Media.Query;

namespace MIT.ECSR.Core.Penawaran.Query
{

    public class GetPenawaranByIdRequest : IRequest<ObjectResponse<PenawaranDetailResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetPenawaranByIdHandler : IRequestHandler<GetPenawaranByIdRequest, ObjectResponse<PenawaranDetailResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetPenawaranByIdHandler(
            ILogger<GetPenawaranByIdHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _context = context;
        }
        public async Task<ObjectResponse<PenawaranDetailResponse>> Handle(GetPenawaranByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<PenawaranDetailResponse> result = new ObjectResponse<PenawaranDetailResponse>();
            try
            {
                var item = await _context.Entity<MIT.ECSR.Data.Model.TrsProgram>().Where(d => d.Id == request.Id)
                                .Include(d=>d.IdJenisProgramNavigation)
                                .Include(d =>d.LokasiNavigation)
                                .Include(d =>d.NamaProgramNavigation)
                                .Include(d=>d.TrsProgramItem)
                                .ThenInclude(d=>d.TrsPenawaranItem)
                                .ThenInclude(d=>d.IdPenawaranNavigation)
                                .FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = new PenawaranDetailResponse()
                    {
                        Program = _mapper.Map<ProgramDetailResponse>(item),
                        Items = _mapper.Map<List<ProgramItemResponse>>(item.TrsProgramItem)
                    };
                    var photo = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "PHOTO_PROGRAM" });
                    if (photo.Succeeded)
                        result.Data.Program.Photo = photo.List.FirstOrDefault();

                    var lampiran = await _mediator.Send(new GetMediaUrlRequest() { Modul = item.Id.ToString(), Tipe = "PROGRAM_LAMPIRAN" });
                    if (lampiran.Succeeded)
                        result.Data.ProgramLampiran = lampiran.List;

                    result.Data.Items.ForEach(x =>
                    {
                        var lampiran = _mediator.Send(new GetMediaUrlRequest() { Modul = x.Id.ToString(), Tipe = "ITEM_PROGRAM" }).GetAwaiter().GetResult();
                        if (lampiran.Succeeded)
                            x.Lampiran = lampiran.List;
                    });

                    result.OK();
                }
                else
                    result.NotFound($"Id MIT.ECSR.Data.Model.TrsProgram {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Program", request.Id);
                result.Error("Failed Get Detail Program", ex.Message);
            }
            return result;
        }
    }
}

