//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MIT.ECSR.Core.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using MIT.ECSR.Data.Model;
using MIT.ECSR.Shared.Attributes;

namespace MIT.ECSR.Core.Response
{
    public partial class ProgramItemDetailResponse : IMapResponse<ProgramItemDetailResponse, MIT.ECSR.Data.Model.TrsProgramItem>
    {
		public Guid Id{ get; set; }
		public double SisaJumlah { get; set; }
		public double Jumlah{ get; set; }
		public string Nama{ get; set; }
		public double Rupiah{ get; set; }
        public double Progress { get; set; }
        public string SatuanUnit{ get; set; }
        public DateTime StartTglPelaksanaan { get; set; }
        public DateTime EndTglPelaksanaan { get; set; }
        public string Lokasi { get; set; }
        public List<MediaUrl> Lampiran { get; set; }
        public List<ProgramPenawaranObject> Penawaran { get; set; }
        public void Mapping(IMappingExpression<MIT.ECSR.Data.Model.TrsProgramItem, ProgramItemDetailResponse> map)
        {
            //use this for mapping
            map.ForMember(d => d.SisaJumlah, opt => opt.MapFrom(s => SetSisa(s)));

        }
		private double SetSisa(TrsProgramItem s)
		{
			return s.Jumlah - (s.TrsPenawaranItem.Sum(d => d.Jumlah));
		}
    }
    public class ProgramPenawaranObject
    {
        public Guid IdPerusahaan { get; set; }
        public MediaUrl Logo { get; set; }
        public string NamaPerusahaan { get; set; }
        public double Unit { get; set; }
        public int StatusPenawaran { get; set; }
    }
}

