//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using MIT.ECSR.Data;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Helper;
using MIT.ECSR.Data.Model;

namespace MIT.ECSR.Core.Program.Command
{

    #region Request
    public class DeleteProgramRequest : IRequest<StatusResponse>
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public string Inputer { get; set; }
    }
    #endregion

    internal class DeleteProgramHandler : IRequestHandler<DeleteProgramRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public DeleteProgramHandler(
            ILogger<DeleteProgramHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<StatusResponse> Handle(DeleteProgramRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var item = await _context.Entity<TrsProgram>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    if (item.Status != (int)ProgramStatusEnum.DRAFT)
                    {
                        result.BadRequest("Cannot Be Deleted because Status is " + ((ProgramStatusEnum)item.Status).ToString());
                        return result;
                    }
                    var delete = await _context.DeleteSave(item);
                    if (delete.Success)
                    {
                        result.OK();
                        await _context.Entity<TrsMedia>().Where(d => d.Modul == request.Id.ToString()).ToListAsync();
                    }
                    else
                        result.BadRequest(delete.Message);

                    return result;
                }
                else
                    result.NotFound($"Id Program {request.Id} Tidak Ditemukan");

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Delete Program", request.Id);
                result.Error("Failed Delete Program", ex.Message);
            }
            return result;
        }
    }
}

