//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using WonderKid.DAL.Interface;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MIT.ECSR.Data;
using MIT.ECSR.Shared.Attributes;
using MIT.ECSR.Core.Helper;
using MIT.ECSR.Core.Request;
using MIT.ECSR.Data.Model;
using DocumentFormat.OpenXml.Spreadsheet;
using MIT.ECSR.Core.Media.Command;
using MIT.ECSR.Shared.Interface;
using MIT.ECSR.Core.Notification.Command;

namespace MIT.ECSR.Core.Program.Command
{

    #region Request
    public class SubmitProgramRequest :IRequest<StatusResponse>
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public string Inputer { get; set; }
        public string RoleName { get; set; }
    }
    #endregion

    internal class SubmitProgramHandler : IRequestHandler<SubmitProgramRequest, StatusResponse>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly IGeneralHelper _helper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public SubmitProgramHandler(
            ILogger<SubmitProgramHandler> logger,
            IMapper mapper,
            IMediator mediator,
            IGeneralHelper helper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _mediator = mediator;
            _helper = helper;
            _context = context;
        }
        public async Task<StatusResponse> Handle(SubmitProgramRequest request, CancellationToken cancellationToken)
        {
            StatusResponse result = new StatusResponse();
            try
            {
                var data = await _context.Entity<MIT.ECSR.Data.Model.TrsProgram>().Where(d => d.Id == request.Id).Include(d=>d.TrsProgramItem)
                    .Include(d => d.NamaProgramNavigation).ThenInclude(d => d.IdJenisProgramNavigation).ThenInclude(d => d.IdSubProgramNavigation).ThenInclude(d => d.IdOpdNavigation)
                    .FirstOrDefaultAsync();
                if (data != null)
                {
                    if (data.TrsProgramItem.Count() == 0)
                    {
                        result.BadRequest("Cannot Be Submited because Kegiatan harus diisi minimal 1 kegiatan!");
                        return result;
                    }

                    if (data.Status != (int)ProgramStatusEnum.DRAFT && data.Status != (int)ProgramStatusEnum.REJECT_VERIFIKASI && data.Status != (int)ProgramStatusEnum.REJECT_APPROVAL)
                    {
                        result.BadRequest("Cannot Be Submit because Status is " + ((ProgramStatusEnum)data.Status).ToString());
                        return result;
                    }
                    if (data.Status == (int)ProgramStatusEnum.DRAFT || data.Status == (int)ProgramStatusEnum.REJECT_VERIFIKASI || data.Status == (int)ProgramStatusEnum.REJECT_APPROVAL)
                    {
                        if (request.RoleName.Contains(RoleName.OPD.ToString()))
                        {
                            data.Status = (int)ProgramStatusEnum.WAITING_APPROVAL;

                            var rolesOpd = await _context.Entity<SetRole>().Where(x => x.Name.Contains(RoleName.BAPPEDA.ToString()))
                                .Include(x => x.SetUser).SelectMany(x => x.SetUser).ToListAsync();

                            foreach (var item in rolesOpd)
                            {
                                await _mediator.Send(new AddNotificationRequest
                                {
                                    Description = $"PROGRAM {data.NamaProgramNavigation.Name} menunggu untuk di approve",
                                    IdUser = item.Id,
                                    Inputer = request.Inputer,
                                    IsOpen = false,
                                    Subject = "MENUNGGU PERSETUJUAN",
                                    Navigation = "/Program"
                                });
                            }
                        }
                        else
                        {
                            data.Status = (int)ProgramStatusEnum.WAITING_VERIFIKASI;

                            var rolesOpd = await _context.Entity<SetRole>().Where(x => x.IdOpd == data.NamaProgramNavigation.IdJenisProgramNavigation.IdSubProgramNavigation.IdOpdNavigation.Id)
                                .Include(x => x.SetUser).SelectMany(x => x.SetUser).ToListAsync();

                            foreach (var item in rolesOpd)
                            {
                                await _mediator.Send(new AddNotificationRequest
                                {
                                    Description = $"PROGRAM {data.NamaProgramNavigation.Name} menunggu untuk di verifikasi",
                                    IdUser = item.Id,
                                    Inputer = request.Inputer,
                                    IsOpen = false,
                                    Subject = "MENUNGGU VERIFIKASI",
                                    Navigation = "/Program"
                                });
                            }

                        }
                    }

                   
                    data.UpdateBy = request.Inputer;
                    data.UpdateDate = DateTime.Now;
                    var save = await _context.UpdateSave(data);
                    if (save.Success)
                        result.OK();
                    else
                        result.BadRequest(save.Message);

                    return result;
                }
                else
                    result.NotFound($"Id Program {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Edit Program", request);
                result.Error("Failed Edit Program", ex.Message);
            }
            return result;
        }
    }
}

